# print('hello world1\nhello world2')
# print('hello '+'sai')
# print('hello'+' '+'sai2')
# print('hello', 'sai3')
print('-' * 20)
print('String manipulation exercise')
print('String concatenation is done with "+" sign')
print('e.g. print("Hello"+"Jenny")')
print('New lines are created using back slash followed by n')
